name: Run regression tests for pdf/a and pdf/ua

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          java-version: 1.11
          distribution: 'temurin'
      - name: Set up
        run: mvn -B -DskipTests=true clean package --file pom.xml
      - name: Run pdf/a and pdf/ua regression tests
        run: java -Djdk.xml.xpathTotalOpLimit=0 -Djdk.xml.xpathExprOpLimit=0 -Djdk.xml.xpathExprGrpLimit=0 -cp "/home/runner/work/veraPDF-integration-tests/veraPDF-integration-tests/veraPDF-pdf-regression-tests/target"/'*' org.verapdf.pdf.regression.tests.PDFRegressionTestUtils

      - name: Notify slack tests succeded
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C03E3JJGLQL
          status: SUCCESS
          color: good

      - name: Notify slack tests failed
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C03E3JJGLQL
          status: FAILED
          color: danger
